version: '3.1'
services:
  database:
    image: 'mongo'
    
    volumes:
      - ./startup/:/docker-entrypoint-initdb.d/
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./:/app/
    ports:
      - '3000:27017'
    restart: always
    command: ['--auth', '-f', '/etc/mongod.conf']
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password